/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'seockmin' at '17. 8. 4 오후 10:59' with Gradle 3.0
 *
 * @author seockmin, @date 17. 8. 4 오후 10:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
